"""add flag for dm

Revision ID: 0cc814ae6daa
Revises: 0a4e397c5073
Create Date: 2021-12-12 20:53:35.784105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc814ae6daa'
down_revision = '0a4e397c5073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('is_channel', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'is_channel')
    # ### end Alembic commands ###
