"""empty message

Revision ID: 81d5b53fcf35
Revises: e3f2b4eb8f90
Create Date: 2021-04-18 20:38:43.761056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d5b53fcf35'
down_revision = 'e3f2b4eb8f90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('messages_receiver_id_fkey', 'messages', type_='foreignkey')
    op.drop_column('messages', 'receiver_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('messages_receiver_id_fkey', 'messages', 'users', ['receiver_id'], ['user_id'])
    # ### end Alembic commands ###
